### ISSUE TITLE
Set up / seed local test database using gradle.

### ISSUE THREAD

**Issue by joethe** [UMM-CSci-3601/3601-lab4_mongo#5]
Clean / populate a local Mongo test database for development. This could be done with a simple gradle task, using mongoimport (and a couple other mongo tools) to clean the db and import some json.

**Comment by joethe** [comment]
This is pretty much done now. HOWEVER: Running the server (using gradle run) does not currently do anything with the database. Users must call the "seedMongoDB" or "clearMongoDB" tasks themselves.

Do we want to tie the database seeding to the run task? Opinions?

**Comment by kklamberty** [comment]
It might be better to have them do this themselves, just so they have the opportunity to be intentional about when they seed the db and when they wipe it. However, if they are to run these themselves, it should probably be included somewhere in the description so that they know how to do so and when it makes sense to do so.

**Comment by kklamberty** [comment]
It looks to me like seeding the DB is described in the readme now, but not clearing the DB. I don't really know when they would want to clear the DB, so I'm not sure where to put that.

**Comment by NicMcPhee** [comment]
It doesn't look like seeding clears the database first, and I think they would _usually_ want to clear before seeding, or they'll get two copies of everything.

**Comment by joethe** [comment]
Seeding the database "depends" on clearing the database. (gradle tasks! :smile: )

**Comment by joethe** [comment]
Done for S17
